name: flame_classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - ipython
  - numpy
  - scipy
  - matplotlib
  - setuptools
  - wheel
  - h5py
  - pandas
  - tensorflow
  - pydot
  
